var fs = require('fs');
var h = fs.readFileSync('out/awards.html', 'utf8');
var idx = h.indexOf('__NEXT_DATA__');
var start = h.indexOf('{', idx);
var end = h.indexOf('</script>', idx);
var d = JSON.parse(h.substring(start, end));
var arr = d.props.pageProps.awardsData;
console.log('Total awards:', arr.length);
console.log('First award_id:', arr[0].award_id);
console.log('First name:', arr[0].award_name || arr[0].award_name_cn);
console.log('First update_time:', arr[0].update_time || '(none)');
