/**
 * 奖项新闻自动采集系统 - 核心配置
 * 
 * T0: 高优先级（有新闻页/RSS，容易抓）
 * T1: 中优先级（有官网新闻页，需爬取）
 * T2: 低优先级（信息更新慢，手动关注）
 */

const AWARD_SOURCES = {
  // ===== T0 高优先级 =====
  t0: [
    {
      award_id: 'if_design',
      award_name_cn: 'iF设计奖',
      award_name_short: 'iF',
      news_url: 'https://ifdesign.com/en/press',
      website: 'https://ifdesign.com',
      country: '德国',
      category_main: '产品设计',
      scrape_type: 'web',
    },
    {
      award_id: 'red_dot',
      award_name_cn: '红点设计奖',
      award_name_short: '红点',
      news_url: 'https://www.red-dot.org/press',
      website: 'https://red-dot.de',
      country: '德国',
      category_main: '产品设计',
      scrape_type: 'web',
    },
    {
      award_id: 'muse_design',
      award_name_cn: 'MUSE设计奖',
      award_name_short: 'MUSE',
      news_url: 'https://design.museaward.com/winners',
      website: 'https://design.museaward.com',
      country: '美国',
      category_main: '综合设计',
      scrape_type: 'web',
    },
    {
      award_id: 'a_design',
      award_name_cn: 'A\' Design Award',
      award_name_short: 'A\' Design',
      news_url: 'https://www.adesignaward.com/pressroom.php',
      website: 'https://competition.adesignaward.com',
      country: '意大利',
      category_main: '综合设计',
      scrape_type: 'web',
    },
    {
      award_id: 'riba_international',
      award_name_cn: 'RIBA国际奖',
      award_name_short: 'RIBA',
      news_url: 'https://www.riba.org/explore/awards/international-awards/',
      website: 'https://www.riba.org',
      country: '英国',
      category_main: '建筑设计',
      scrape_type: 'web',
    },
    {
      award_id: 'architizer_a',
      award_name_cn: 'Architizer A+Awards',
      award_name_short: 'A+',
      news_url: 'https://awards.architizer.com/a/blog',
      website: 'https://awards.architizer.com',
      country: '美国',
      category_main: '建筑设计',
      scrape_type: 'web',
    },
    {
      award_id: 'g_mark',
      award_name_cn: 'G-Mark奖（优良设计奖）',
      award_name_short: 'G-Mark',
      news_url: 'https://www.g-mark.org/en/news/',
      website: 'https://www.g-mark.org',
      country: '日本',
      category_main: '产品设计',
      scrape_type: 'web',
    },
    {
      award_id: 'good_design_au',
      award_name_cn: 'Good Design奖',
      award_name_short: 'Good Design',
      news_url: 'https://good-design.org/news/',
      website: 'https://good-design.org',
      country: '美国',
      category_main: '产品设计',
      scrape_type: 'web',
    },
    {
      award_id: 'waf',
      award_name_cn: '世界建筑节奖',
      award_name_short: 'WAF',
      news_url: 'https://worldarchitecturefestival.com/news',
      website: 'https://worldarchitecturefestival.com',
      country: '新加坡',
      category_main: '建筑设计',
      scrape_type: 'web',
    },
    {
      award_id: 'dandad',
      award_name_cn: 'D&AD奖',
      award_name_short: 'D&AD',
      news_url: 'https://www.dandad.org/en/d-ad-awards/news',
      website: 'https://www.dandad.org',
      country: '英国',
      category_main: '视觉传达',
      scrape_type: 'web',
    },
    {
      award_id: 'spark',
      award_name_cn: 'Spark设计奖',
      award_name_short: 'Spark',
      news_url: 'https://www.sparkawards.com/News',
      website: 'https://www.sparkawards.com',
      country: '美国',
      category_main: '产品设计',
      scrape_type: 'web',
    },
    {
      award_id: 'prix_versailles',
      award_name_cn: '凡尔赛奖',
      award_name_short: 'Versailles',
      news_url: 'https://www.prix-versailles.com/en/news/',
      website: 'https://www.prix-versailles.com',
      country: '法国',
      category_main: '建筑设计',
      scrape_type: 'web',
    },
    {
      award_id: 'k_design',
      award_name_cn: 'K-Design奖',
      award_name_short: 'K-Design',
      news_url: 'https://kdesignaward.com/News',
      website: 'https://kdesignaward.com',
      country: '韩国',
      category_main: '综合设计',
      scrape_type: 'web',
    },
    {
      award_id: 'loop_design',
      award_name_cn: 'Loop设计奖',
      award_name_short: 'Loop',
      news_url: 'https://www.loopdesignawards.com/news',
      website: 'https://www.loopdesignawards.com',
      country: '泰国',
      category_main: '综合设计',
      scrape_type: 'web',
    },
    {
      award_id: 'ny_design',
      award_name_cn: '纽约设计奖',
      award_name_short: 'NY Design',
      news_url: 'https://nydesignawards.com/winners',
      website: 'https://nydesignawards.com',
      country: '美国',
      category_main: '产品设计',
      scrape_type: 'web',
    },
  ],
};

module.exports = { AWARD_SOURCES };
